# Generated by Django 5.1.2 on 2024-11-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
        ("lesson_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonassigment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_assignment",
                to="lesson.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="lessondescription",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_description",
                to="lesson.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="lessonquiz",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_quiz",
                to="lesson.lesson",
            ),
        ),
    ]
