# Generated by Django 5.1.2 on 2024-11-24 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
        ("lesson_content", "0003_remove_lessonquiz_average_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonassigment",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_assignment",
                to="lesson.lesson",
            ),
        ),
    ]
