# Generated by Django 5.1.2 on 2024-11-26 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_rename_name_lesson_topic"),
        ("lesson_content", "0005_rename_lessonquiz_lessonquestion_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonAssigment",
            new_name="LessonAssignment",
        ),
        migrations.RenameModel(
            old_name="LessonQuestion",
            new_name="LessonQuiz",
        ),
        migrations.RenameField(
            model_name="lessonintroduction",
            old_name="introduction",
            new_name="description",
        ),
    ]
