# Generated by Django 5.1.2 on 2024-11-26 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_content", "0006_rename_lessonassigment_lessonassignment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizoption",
            old_name="option",
            new_name="answer",
        ),
    ]
