# Generated by Django 5.1.2 on 2024-12-03 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_content", "0008_studentprogress_delete_usserprogress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProgress",
        ),
    ]
