# Generated by Django 5.1.2 on 2024-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
