# Generated by Django 5.1.2 on 2024-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_course_description_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="creator_state",
            field=models.CharField(default="update", max_length=60),
        ),
    ]
