# Generated by Django 5.1.2 on 2024-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_course_creator_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
