# Generated by Django 5.1.2 on 2024-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
