# Generated by Django 5.1.2 on 2024-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_course_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.CharField(default="", max_length=255),
        ),
    ]
