# Generated by Django 5.1.2 on 2024-11-26 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="topic",
        ),
    ]
